name: ans_scoring
channels:
  - conda-forge
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.2.2
  - libffi=3.4.2
  - libsqlite=3.45.1
  - libzlib=1.2.13
  - ncurses=6.4
  - openssl=3.2.1
  - pip=24.0
  - python=3.9.18
  - readline=8.2
  - setuptools=69.1.1
  - tk=8.6.13
  - tzdata=2024a
  - wheel=0.42.0
  - xz=5.2.6
  - pip:
      - absl-py==2.1.0
      - aiohttp==3.9.3
      - aiosignal==1.3.1
      - anndata==0.10.9
      - anndata2ri==1.3.1
      - anyio==4.3.0
      - appdirs==1.4.4
      - appnope==0.1.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - array-api-compat==1.9.1
      - arrow==1.3.0
      - astroid==2.15.8
      - asttokens==2.4.1
      - async-lru==2.0.4
      - async-timeout==4.0.3
      - attrs==23.2.0
      - babel==2.14.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - certifi==2024.2.2
      - cffi==1.16.0
      - cftime==1.6.3
      - charset-normalizer==3.3.2
      - chex==0.1.85
      - comm==0.2.1
      - contextlib2==21.6.0
      - contourpy==1.2.0
      - cycler==0.12.1
      - datacache==1.4.1
      - debugpy==1.8.1
      - decorator==5.1.1
      - decoupler==1.6.0
      - defusedxml==0.7.1
      - dill==0.3.9
      - docrep==0.3.2
      - et-xmlfile==1.1.0
      - etils==1.5.2
      - exceptiongroup==1.2.0
      - executing==2.0.1
      - fastjsonschema==2.19.1
      - filelock==3.13.1
      - flax==0.8.1
      - fonttools==4.49.0
      - fqdn==1.5.1
      - frozenlist==1.4.1
      - fsspec==2024.2.0
      - geoparse==2.0.3
      - get-annotations==0.1.2
      - gssnng==0.5.0
      - gtfparse==2.5.0
      - gdown==5.2.0
      - h11==0.14.0
      - h5py==3.10.0
      - harmonypy==0.0.9
      - httpcore==1.0.4
      - httpx==0.27.0
      - idna==3.6
      - igraph==0.11.4
      - imageio==2.34.0
      - importlib-metadata==7.0.2
      - importlib-resources==6.1.3
      - ipykernel==6.29.3
      - ipython==8.18.1
      - isoduration==20.11.0
      - isort==5.13.2
      - jax==0.4.25
      - jaxlib==0.4.25
      - jedi==0.19.1
      - jinja2==3.1.3
      - joblib==1.3.2
      - json5==0.9.22
      - jsonpointer==2.4
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.0
      - jupyter-core==5.7.1
      - jupyter-events==0.9.0
      - jupyter-lsp==2.2.4
      - jupyter-server==2.13.0
      - jupyter-server-terminals==0.5.2
      - jupyterlab==4.1.4
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.25.3
      - kiwisolver==1.4.5
      - lazy-loader==0.4
      - lazy-object-proxy==1.10.0
      - legacy-api-wrap==1.4
      - leidenalg==0.10.2
      - lightning==2.1.4
      - lightning-utilities==0.10.1
      - llvmlite==0.42.0
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.8.3
      - matplotlib-inline==0.1.6
      - matplotlib-venn==0.11.10
      - mccabe==0.7.0
      - mdurl==0.1.2
      - memoized-property==1.0.3
      - memory-profiler==0.61.0
      - mistune==3.0.2
      - ml-collections==0.1.1
      - ml-dtypes==0.3.2
      - mock==5.1.0
      - mpmath==1.3.0
      - msgpack==1.0.8
      - mudata==0.2.3
      - multidict==6.0.5
      - multipledispatch==1.0.0
      - natsort==8.4.0
      - nbclient==0.9.0
      - nbconvert==7.16.2
      - nbformat==5.9.2
      - nest-asyncio==1.6.0
      - netcdf4==1.6.5
      - networkx==3.2.1
      - notebook==7.1.1
      - notebook-shim==0.2.4
      - numba==0.59.0
      - numpy==1.26.4
      - numpyro==0.14.0
      - openpyxl==3.1.2
      - opt-einsum==3.3.0
      - optax==0.2.1
      - orbax-checkpoint==0.5.3
      - overrides==7.7.0
      - packaging==24.0
      - pandas==1.5.3
      - pandocfilters==1.5.1
      - parso==0.8.3
      - patsy==0.5.6
      - pexpect==4.9.0
      - pillow==10.2.0
      - platformdirs==4.2.0
      - polars==0.20.31
      - progressbar33==2.4
      - prometheus-client==0.20.0
      - prompt-toolkit==3.0.43
      - protobuf==4.25.3
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyarrow==14.0.2
      - pycparser==2.21
      - pydeseq2==0.4.7
      - pyensembl==2.3.13
      - pygments==2.17.2
      - pygmt==0.11.0
      - pylint==2.17.7
      - pynndescent==0.5.11
      - pyparsing==3.1.2
      - pyqt5==5.15.10
      - pyqt5-qt5==5.15.13
      - pyqt5-sip==12.13.0
      - pyreadr==0.5.0
      - pyro-api==0.1.2
      - pyro-ppl==1.9.0
      - python-dateutil==2.9.0.post0
      - python-json-logger==2.0.7
      - pytorch-lightning==2.2.1
      - pytz==2024.1
      - pyyaml==6.0.1
      - pyzmq==25.1.2
      - referencing==0.33.0
      - requests==2.31.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.7.1
      - rpds-py==0.18.0
      - rpy2==3.5.15
      - scanpy==1.10.3
      - scikit-image==0.22.0
      - scikit-learn==1.4.1.post1
      - scikit-misc==0.1.4
      - scipy==1.12.0
      - scprep==1.2.3
      - scvi-tools==1.1.2
      - seaborn==0.13.2
      - send2trash==1.8.2
      - serializable==0.4.1
      - session-info==1.0.0
      - signaturescoring==0.1.0
      - simplejson==3.19.3
      - six==1.16.0
      - sniffio==1.3.1
      - soupsieve==2.5
      - stack-data==0.6.3
      - statannotations==0.6.0
      - statsmodels==0.14.1
      - stdlib-list==0.10.0
      - sympy==1.12
      - tensorstore==0.1.54
      - terminado==0.18.0
      - texttable==1.7.0
      - threadpoolctl==3.3.0
      - tifffile==2024.2.12
      - tinycss2==1.2.1
      - tinytimer==0.0.0
      - tomli==2.0.1
      - tomlkit==0.13.2
      - toolz==0.12.1
      - torch==2.2.1
      - torchmetrics==1.3.1
      - tornado==6.4
      - tqdm==4.66.2
      - traitlets==5.14.1
      - typechecks==0.1.0
      - types-python-dateutil==2.8.19.20240106
      - typing-extensions==4.10.0
      - tzlocal==5.2
      - umap-learn==0.5.5
      - uri-template==1.3.0
      - urllib3==2.2.1
      - wcwidth==0.2.13
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.7.0
      - wrapt==1.17.0
      - xarray==2024.3.0
      - yarl==1.9.4
      - zipp==3.17.0
